name: Scrape and Parse

on:
  schedule:
    - cron: '0 0 * * *' # run once every day at midnight UTC
  workflow_dispatch: # run manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Scrape data
        run: python scrape.py

      - name: Evaluate downloaded file
        run: |
          python evaluate_downloaded.py tmp/$(date +"%Y-%m-%d").csv
        
      - name: Check if files were created
        id: check_files
        run: |
          if [[ $(git diff --exit-code data/raw) ]]; then
            echo "New files were created. Continuing with the workflow."
            echo "::set-output name=continue::true"
          else
            echo "No new files were created. Aborting the workflow."
            echo "::set-output name=continue::false"
            exit 0
          fi

      - name: Parse raw data
        if: steps.check_files.outputs.continue == 'true'
        run: python parse_raw.py data/raw/$(date +"%Y-%m-%d").csv

      - name: Send Slack notification with summary
        if: steps.check_files.outputs.continue == 'true'
        run: python summarize_update.py data/parsed/$(date +"%Y-%m-%d") data/parsed/latest

      - name: Copy parsed data to data/parsed/latest
        if: steps.check_files.outputs.continue == 'true'
        run: cp data/parsed/$(date +"%Y-%m-%d")/* data/parsed/latest/

      - name: Commit and push changes
        if: steps.check_files.outputs.continue == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update data"
          add: "data"
          branch: main
          push: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send Slack notification if nothing changed
        if: steps.check_files.outputs.continue == 'false'
        run: python post_to_slack.py "Kollade Panorama. Ingen ny data."
